server:
  port: 4040

spring:
  application:
    name: mvflix-movies

  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/mvflix_movies_db
    username: db_rw
    password: 12345678

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mvflix_movies_db
    username: db_migrator
    password: 12345678

services:
  authorization:
    url: ${AUTHORIZATION_URL:http://127.0.0.1:9090}

movies:
  draft:
    time-to-live: 24h
    cleanup-check-ms: 3600000

security:
  oauth2:
    jwk-set-uri: ${SECURITY_OAUTH2_JWK_SET_URI:http://127.0.0.1:9090/oauth2/jwks}

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    org.springframework.security.oauth2: debug
    org.springframework.data.redis: debug
    jakarta.jms: debug