spring:
  application:
    name: mvflix-users

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mvflix_users_db
    username: db_rw
    password: 12345678

  datasource:
    url: jdbc:postgresql://localhost:5432/mvflix_users_db
    username: db_migrator
    password: 12345678

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9090
          jwk-set-uri: http://127.0.0.1:9090/oauth2/jwks

services:
  authorization:
    url: ${AUTHORIZATION_URL:http://localhost:9090}

server:
  port: 8080
