spring:
  application:
    name: mvflix-users

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mvflix_users_db
    username: db_rw
    password: 12345678

  datasource:
    url: jdbc:postgresql://localhost:5432/mvflix_users_db
    username: db_migrator
    password: 12345678

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
          jwk-set-uri: http://localhost:9090/oauth2/jwks

security:
  oauth2:
    client-registration-id: users-app
    client-id: users-service
    client-secret: ${SECURITY_OAUTH2_CLIENT_SECRET:super-secret}

services:
  authorization:
    url: ${AUTHORIZATION_URL:http://localhost:9090}
  storage:
    url: ${STORAGE_URL:http://localhost:6060}

server:
  port: 8080
