server:
  port: 6060

api:
  path:
    base: /api/v1/movie

spring:
  application:
    name: powercine

  autoconfigure:
    exclude:
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      #- org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mvflix_uploads_db
    username: db_rw
    password: 12345678

  datasource:
    url: jdbc:postgresql://localhost:5432/mvflix_uploads_db
    username: db_migrator
    password: 12345678

services:
  authorization:
    url: ${AUTHORIZATION_URL:http://localhost:9090}
  users:
    url: ${USERS_URL:http://localhost:8080}

security:
  oauth2:
    client-registration-id: storage-app
    client-id: storage-service
    client-secret: ${SECURITY_OAUTH2_CLIENT_SECRET:super-secret}
    jwk-set-uri: ${SECURITY_OAUTH2_JWK_SET_URI:http://localhost:9090/oauth2/jwks}

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: admin
  secret-key: admin123
  bucket: uploads
  webhook-token: ${MINIO_WEBHOOK_TOKEN:dev-webhook-secret}

storage:
  session:
    time-to-live: 60m
    expiration-check-ms: 60000

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    org.springframework.security.oauth2: debug
    org.springframework.data.redis: debug
    jakarta.jms: debug
